language: node_js
node_js:
  - "20"
dist: Windows
services: 
 - mongodb
env:
 - PORT: 5000
install:
 - npm install
 - npm run build
script: 
 - nohup npm run start &
 - sleep 3
 - npm run test   